<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.5.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="John Christian Gaby">

  
  
  
    
  
  <meta name="description" content="In this blogpost, I describe the calculation of prokaryotic genome weight and determine genome mass variation due to GC content variation to be negligible in double stranded genomes.">

  
  <link rel="alternate" hreflang="en-us" href="https://chrisgaby.github.io/post/prokaryotic-genome-weight/">

  


  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin="anonymous">
    

    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.04a87a1cb9027e3c50f566322527c56f.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-177026255-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="https://chrisgaby.github.io/post/prokaryotic-genome-weight/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="John Christian Gaby, PhD">
  <meta property="og:url" content="https://chrisgaby.github.io/post/prokaryotic-genome-weight/">
  <meta property="og:title" content="Prokaryotic Genome Weight | John Christian Gaby, PhD">
  <meta property="og:description" content="In this blogpost, I describe the calculation of prokaryotic genome weight and determine genome mass variation due to GC content variation to be negligible in double stranded genomes."><meta property="og:image" content="https://chrisgaby.github.io/img/icon-192.png">
  <meta property="twitter:image" content="https://chrisgaby.github.io/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-09-09T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-09-16T00:08:03&#43;02:00">
  

  


    






  





  









<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://chrisgaby.github.io/post/prokaryotic-genome-weight/"
  },
  "headline": "Prokaryotic Genome Weight",
  
  "datePublished": "2020-09-09T00:00:00Z",
  "dateModified": "2020-09-16T00:08:03+02:00",
  
  "publisher": {
    "@type": "Organization",
    "name": "John Christian Gaby, PhD",
    "logo": {
      "@type": "ImageObject",
      "url": "https://chrisgaby.github.io/img/icon-512.png"
    }
  },
  "description": "In this blogpost, I describe the calculation of prokaryotic genome weight and determine genome mass variation due to GC content variation to be negligible in double stranded genomes."
}
</script>

  

  


  


  





  <title>Prokaryotic Genome Weight | John Christian Gaby, PhD</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/">John Christian Gaby, PhD</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>About me</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/files/cv.pdf"><span>CV</span></a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Prokaryotic Genome Weight</h1>

  
  <p class="page-subtitle">Calculation of prokaryotic genome weight and the negligible influence of genome GC%</p>
  

  
    



<div class="article-metadata">

  
  
  
  
  <div>
    



  <span><a href="/authors/john-christian-gaby/">John Christian Gaby</a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Wed, Sep 16, 2020
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    12 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/categories/genome-calculations/">genome calculations</a></span>
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://chrisgaby.github.io/post/prokaryotic-genome-weight/&amp;text=Prokaryotic%20Genome%20Weight" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://chrisgaby.github.io/post/prokaryotic-genome-weight/&amp;t=Prokaryotic%20Genome%20Weight" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Prokaryotic%20Genome%20Weight&amp;body=https://chrisgaby.github.io/post/prokaryotic-genome-weight/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://chrisgaby.github.io/post/prokaryotic-genome-weight/&amp;title=Prokaryotic%20Genome%20Weight" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Prokaryotic%20Genome%20Weight%20https://chrisgaby.github.io/post/prokaryotic-genome-weight/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=https://chrisgaby.github.io/post/prokaryotic-genome-weight/&amp;title=Prokaryotic%20Genome%20Weight" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>In a previous blogpost, I explored <a href="/post/prokaryotic-genome-size/index.html">prokaryotic genome size</a> (i.e. the length of a prokaryotic genome in number of nucleotides). In this blogpost, I will take the previously determined genome sizes and multiply them against the molecular weight of a DNA base pair to arrive at the mass of a prokaryotic genome. I start by examining the structural components of DNA (the 4 nitrogenous bases, a pentose sugar called deoxyribose, and phosphate) and their elemental composition, and then I will determine the amount of mass variation that could result from natural variation in genome GC content.</p>
</div>
<div id="determining-the-number-of-atoms-of-each-element-in-a-dna-base-pair" class="section level2">
<h2>Determining the Number of Atoms of Each Element in a DNA Base Pair</h2>
<p>DNA is a macromolecule that consists of a sequence of chemically linked nucleotides. Nucleotides are comprised of a nucleoside linked to a phosphate. Nucleosides consist of a nitrogenous base such as a purine (A or G) or a pyrimidine (T or C) linked to a sugar, which in the case of DNA is the pentose sugar deoxyribose. Hence, there are 3 components of DNA:</p>
<ol style="list-style-type: decimal">
<li>Phosphate</li>
<li>Pentose sugar deoxyribose</li>
<li>Nitrogenous bases Adenine, Thymine, Cytosine, and Guanine</li>
</ol>
<p>Whereas each nucleotide in DNA contains phosphate and deoxyribose, the nitrogenous base will vary. Indeed, it this variation in the sequence of nitrogenous bases along the length of a genome that determines the information content of the macromolecule and ultimately the identity of the organism.</p>
<p>Let’s take a closer look at the 3 components of DNA by examining their molecular structure, determining the number of atoms of each element in their structure, and then calculating their molecular mass.</p>
<div id="the-phosphate" class="section level3">
<h3>The Phosphate</h3>
<p>Phosphate is the simplest of the 3 DNA components, consting of 1 phosphorus atom and 4 oxygen atoms:</p>
<div class="figure">
<img src="/img/PO4.jpg" alt="The structure of a lone phosphate molecule." />
<p class="caption">The structure of a lone phosphate molecule.</p>
</div>
<p>This view of a phosphate molecule was generated using <a href="http://jmol.sourceforge.net/">Jmol</a> from an <a href="/files/PO4_ideal.sdf">sdf format file representing the structure of PO<sub>4</sub></a>. The sdf file was downloaded from the RCSB Protein Databank webpage for <a href="https://www.rcsb.org/ligand/PO4">PO<sub>4</sub></a>.</p>
<p>The colors in the molecular structures presented in this blogpost correspond to the CPK (Corey, Pauling, Koltun) color scheme:</p>
<p><span style="color: rgb(144,144,144); font-size:20pt;">carbon is grey</span></p>
<p><span style="color: rgb(255,255,255); background-color: black; font-size:20pt;">hydrogen is white</span></p>
<p><span style="color: rgb(255,0,31); font-size:20pt;">oxygen is red</span></p>
<p><span style="color: rgb(22,88,240); font-size:20pt;">nitrogen is blue</span></p>
<p><span style="color: rgb(255,123,44); font-size:20pt;">phosphorus is orange</span></p>
</div>
<div id="the-pentose-sugar-deoxyribose" class="section level3">
<h3>The Pentose Sugar Deoxyribose</h3>
<p>The pentose sugar deoxyribose, along with phosphate, form the backbone of DNA by linking the nucleotides. In DNA, deoxyribose forms a furanose ring as in this view of the structure of beta-D-2-Deoxyribose:</p>
<p><img src="/img/beta-D-2-Deoxyribose.jpg" alt="The structure of beta-D-2-Deoxyribose" />.</p>
<p>I downloaded the <a href="/files/beta-D-2-Deoxyribose.sdf">sdf format file for the chemical structure of beta-D-2-Deoxyribose</a> from <a href="https://pubchem.ncbi.nlm.nih.gov/compound/439576">PubChem</a> in order to produce the above molecular structure image within <a href="http://jmol.sourceforge.net/">Jmol</a>.</p>
<p>The chemical formula for <a href="https://pubchem.ncbi.nlm.nih.gov/compound/439576">beta-D-2-Deoxyribose at PubChem</a> is C<sub>5</sub>H<sub>10</sub>O<sub>4</sub>.</p>
<p>I will now calculate the molecular mass of beta-D-2-Deoxyribose. For reference, these are the atomic masses of the elements in DNA:</p>
<table>
<thead>
<tr class="header">
<th>Element</th>
<th>Atomic Mass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C</td>
<td>12.0107</td>
</tr>
<tr class="even">
<td>O</td>
<td>15.9994</td>
</tr>
<tr class="odd">
<td>N</td>
<td>14.0067</td>
</tr>
<tr class="even">
<td>P</td>
<td>30.9738</td>
</tr>
<tr class="odd">
<td>H</td>
<td>1.0079</td>
</tr>
</tbody>
</table>
<p>The mass of each element is conveniently accessible via the <code>mass()</code> function in the R package <code>PeriodicTable</code>.</p>
<pre class="r"><code>library(PeriodicTable)

# Create the data frame based on the formula for deoxyribose.
deoxyribose.df1&lt;- data.frame(element = c(&quot;C&quot;,&quot;H&quot;,&quot;O&quot;), freq = c(5,10,4))

# Add a 3rd column that is the atomic mass of each element.
deoxyribose.df2 &lt;- cbind(deoxyribose.df1, MW = PeriodicTable::mass(deoxyribose.df1[1:nrow(deoxyribose.df1),1]))

# Add a 4th column that is the total molecular weight of each element
# in the deoxyribose molecule. This is the product of the atomic
# mass and the number of atoms of each element.
deoxyribose.df3 &lt;- cbind(deoxyribose.df2, MW.tot = deoxyribose.df2[,2] * deoxyribose.df2[,3])

deoxyribose.df3</code></pre>
<pre><code>##   element freq       MW  MW.tot
## 1       C    5 12.01070 60.0535
## 2       H   10  1.00794 10.0794
## 3       O    4 15.99940 63.9976</code></pre>
<pre class="r"><code>sum(deoxyribose.df3[,&quot;MW.tot&quot;])</code></pre>
<pre><code>## [1] 134.1305</code></pre>
<p>The molecular weight of deoxyribose is determined to be 134.1305 g/mol, which matches the molecular weight for <a href="https://pubchem.ncbi.nlm.nih.gov/compound/439576">beta-D-2-Deoxyribose at PubChem</a>.</p>
</div>
<div id="the-nitrogenous-bases" class="section level3">
<h3>The Nitrogenous Bases</h3>
<p>I’ll obtain the number of C, N, O, and H atoms in each nitrogenous base by using a column from the Protein Data Bank (PDB) files for the molecular model of each base. The PDB files for each nitrogenous base were obtained from the “required case study files” for an online <a href="https://www.ks.uiuc.edu/Training/CaseStudies/">DNA case study</a> written by Leonardo Trabuco and Elizabeth Villa.</p>
<div id="adenine" class="section level4">
<h4>Adenine</h4>
<div class="figure">
<img src="/img/adenine.jpg" alt="The molecular structure of adenine." />
<p class="caption">The molecular structure of adenine.</p>
</div>
<p>I will obtain the number of atoms of each element in the adenine strucutre by parsing its <a href="/files/adenine.pdb">PDB file</a>.</p>
<pre class="r"><code>library(tidyverse)

# Read the adenine PDB file into a tibble, skipping the first row
# that causes the column of interest to be missed.
adenine &lt;- read_table2(file = &quot;../../static/files/adenine.pdb&quot;, 
                       col_names = FALSE, 
                       skip = 1)

# Remove the last row that only contains &quot;end&quot;.
A.atoms &lt;- adenine[seq(1,(nrow(adenine)-1)),12]

# Make a table with the total number of atoms of each type.
A.table &lt;- table(A.atoms)
A.table</code></pre>
<pre><code>## A.atoms
## C H N 
## 5 5 5</code></pre>
<p>The results corroborate with the C<sub>5</sub>N<sub>5</sub>H<sub>5</sub> chemical formula for <a href="https://pubchem.ncbi.nlm.nih.gov/compound/190">adenine on PubChem</a>.</p>
<p>Next, I will calculate the total molar mass of the adenine molecule. To do this, I will need the atomic mass of each element:</p>
<pre class="r"><code>library(PeriodicTable)

# Change to a data frame.
A.df &lt;- as.data.frame(A.table)

# Add a 3rd column that is the atomic mass of each element.
A.df2 &lt;- cbind(A.df, MW = PeriodicTable::mass(A.df[1:nrow(A.df),1]))

# Add a 4th column that is the total molecular weight of each element
# in the nucleotide base molecule. This is the product of the atomic
# mass and the number of atoms of each element.
A.df3 &lt;- cbind(A.df2, MW.tot = A.df2[,2] * A.df2[,3])

A.df3</code></pre>
<pre><code>##   A.atoms Freq       MW  MW.tot
## 1       C    5 12.01070 60.0535
## 2       H    5  1.00794  5.0397
## 3       N    5 14.00670 70.0335</code></pre>
<pre class="r"><code>sum(A.df3[,&quot;MW.tot&quot;])</code></pre>
<pre><code>## [1] 135.1267</code></pre>
<p>Hence, the molar mass of adenine is determined to be 135.1267 g/mol, which corroborates with the molar mass of 135.13 g/mol listed for <a href="https://pubchem.ncbi.nlm.nih.gov/compound/190">adenine on PubChem</a>.</p>
</div>
<div id="thymine-cytosine-and-guanine" class="section level4">
<h4>Thymine, Cytosine, and Guanine</h4>
<div class="figure">
<img src="/img/thymine.jpg" alt="The molecular structure of thymine." />
<p class="caption">The molecular structure of thymine.</p>
</div>
<div class="figure">
<img src="/img/cytosine.jpg" alt="The molecular structure of cytosine." />
<p class="caption">The molecular structure of cytosine.</p>
</div>
<div class="figure">
<img src="/img/guanine.jpg" alt="The molecular structure of guanine." />
<p class="caption">The molecular structure of guanine.</p>
</div>
<p>I will now adapt the previous code for determining the molar mass of adenine into a custom function named <code>nucMolarMass</code>, which takes as input the PDB file, extracts the column that lists each atom in the molecule, and sums the mass of all atoms to obtain the overall molar mass for the nitrogenous base.</p>
<pre class="r"><code>library(tidyverse)
library(PeriodicTable)

nucMolarMass &lt;- function(filename) 
{
 
# Read the adenine PDB file into a tibble, skipping the first row
# that causes the column of interest to be missed. 
 nuc &lt;- read_table2(file = paste0(&quot;./static/files/&quot;,filename), 
                       col_names = FALSE, 
                       skip = 1)

# Remove the last row that only contains &quot;end&quot;.
nuc.atoms &lt;- nuc[seq(1,(nrow(nuc)-1)),12]

# Make a table with the total number of atoms of each type.
nuc.table &lt;- table(nuc.atoms)

# Change to a data frame.
nuc.df &lt;- as.data.frame(nuc.table)

# Add a 3rd column that is the atomic mass of each element.
nuc.df2 &lt;- cbind(nuc.df, MW = PeriodicTable::mass(nuc.df[1:nrow(nuc.df),1]))

# Add a 4th column that is the total molecular weight of each element
# in the nucleotide base molecule. This is the product of the atomic
# mass and the number of atoms of each element.
nuc.df3 &lt;- cbind(nuc.df2, MW.tot = nuc.df2[,2] * nuc.df2[,3])

sum(nuc.df3[,&quot;MW.tot&quot;])
 
}

# Set the working directory to prevent issues with file input.
setwd(&quot;/home/chrisgaby/github/My_Website/&quot;)

# Print the adenine molar mass.
T.MM &lt;- nucMolarMass(&quot;thymine.pdb&quot;)
print(paste(&quot;The molar mass for thymine is&quot;, T.MM))</code></pre>
<pre><code>## [1] &quot;The molar mass for thymine is 126.11334&quot;</code></pre>
<pre class="r"><code># Print the guanine molar mass.
G.MM &lt;- nucMolarMass(&quot;guanine.pdb&quot;)
print(paste(&quot;The molar mass for guanine is&quot;, G.MM))</code></pre>
<pre><code>## [1] &quot;The molar mass for guanine is 151.1261&quot;</code></pre>
<pre class="r"><code># Print the cytosine molar mass.
C.MM &lt;- nucMolarMass(&quot;cytosine.pdb&quot;)
print(paste(&quot;The molar mass for cytosine is&quot;, C.MM))</code></pre>
<pre><code>## [1] &quot;The molar mass for cytosine is 111.102&quot;</code></pre>
<p>On PubChem, the molar mass of <a href="https://pubchem.ncbi.nlm.nih.gov/compound/1135">thymine</a> is 126.11g/mol, of <a href="https://pubchem.ncbi.nlm.nih.gov/compound/135398634">guanine</a> is 151.13 g/mol, and of <a href="https://pubchem.ncbi.nlm.nih.gov/compound/597">cytosine</a> is 111.1 g/mol, which all corroborate with the results above.</p>
<p>You can download the PDB files for <a href="/files/thymine.pdb">thymine</a>, <a href="/files/cytosine.pdb">cytosine</a>, and <a href="/files/guanine.pdb">guanine</a>.</p>
</div>
</div>
</div>
<div id="dna-base-pairing" class="section level2">
<h2>DNA Base Pairing</h2>
<p>Hence, DNA may contain adenine (A), thymine (T), cytosine (C), and guanine (G) bases. In double stranded DNA there is complementarity between strands whereby A forms a linkage with T that consists of 2 hydrogen bonds, whereas G forms a linkage with C that consists of 3 hydrogen bonds. The AT and GC base pairing is illustrated in the following molecular structure images:</p>
<div class="figure">
<img src="/img/ATBasePair.png" alt="An AT base pair." />
<p class="caption">An AT base pair.</p>
</div>
<div class="figure">
<img src="/img/GCBasePair.png" alt="A GC base pair." />
<p class="caption">A GC base pair.</p>
</div>
<div class="figure">
<img src="/img/ATandGCBasePair.png" alt="An AT and a GC base pair shown together." />
<p class="caption">An AT and a GC base pair shown together.</p>
</div>
<p>These images of DNA base pairs were obtained online from <a href="http://MolviZ.Org">MolviZ.Org</a> on the <a href="http://biomodel.uah.es/en/model4/dna/index.htm">DNA Structure page</a> by Eric Martz and Angel Herráez, wherein their <a href="http://biomodel.uah.es/en/model1/dna/pares.htm">Nucleotide Pairing model</a> is particularly useful for illustrating the basic principles of DNA molecular composition and geometry.</p>
</div>
<div id="the-weight-of-an-at-vs.a-gc-base-pair" class="section level2">
<h2>The Weight of an AT vs. a GC Base Pair</h2>
<p>We can see from the images and calculations above that the 4 nitrogenous bases vary in molecular structure and in the number of atoms of each element that comprise them, and hence there are differences in the molar mass of each nitrogenous base.</p>
<p>Now let’s examine the molar mass of an AT and a GC base pair to determine whether they may have substantially different masses. Here I’ll use the PDB file for a GC base pair to extract the number of atoms of each element in the same manner as for calculating the molar mass of the nitrogenous bases.</p>
<pre class="r"><code>library(tidyverse)

# Read the CG base pair PDB file into a tibble. Skip the first 2 rows that
# do not contain the desired data.
CG &lt;- read_table2(file = &quot;../../static/files/c-g_b.pdb&quot;, 
                       col_names = FALSE, 
                       skip = 2)

# Only the rows with ATOM in column 1 are the ones that should be retained.
CG2 &lt;- CG[grep(&quot;ATOM&quot;,CG$X1), ]

CG.atoms&lt;- substr(as.data.frame(CG2)[,3], 1, 1)

# Make a table with the total number of atoms of each type.
CG.table &lt;- table(CG.atoms)
CG.table</code></pre>
<pre><code>## CG.atoms
##  C  H  N  O  P 
## 19 24  8 12  2</code></pre>
<p>It looks like the GC base pair has the formula C<sub>19</sub>H<sub>24</sub>N<sub>8</sub>O<sub>12</sub>P<sub>2</sub>. Let’s determine the molecular mass of the GC base pair using the following code, which is similar to how we calculated the molecular mass of adenine above.</p>
<pre class="r"><code>library(PeriodicTable)

# Change to a data frame.
CG.df &lt;- as.data.frame(CG.table)

# Add a 3rd column that is the atomic mass of each element.
CG.df2 &lt;- cbind(CG.df, MW = PeriodicTable::mass(CG.df[1:nrow(CG.df),1]))

# Add a 4th column that is the total molecular weight of each element
# in the nucleotide base molecule. This is the product of the atomic
# mass and the number of atoms of each element.
CG.df3 &lt;- cbind(CG.df2, MW.tot = CG.df2[,2] * CG.df2[,3])

CG.df3</code></pre>
<pre><code>##   CG.atoms Freq       MW    MW.tot
## 1        C   19 12.01070 228.20330
## 2        H   24  1.00794  24.19056
## 3        N    8 14.00670 112.05360
## 4        O   12 15.99940 191.99280
## 5        P    2 30.97376  61.94752</code></pre>
<pre class="r"><code>sum(CG.df3[,&quot;MW.tot&quot;])</code></pre>
<pre><code>## [1] 618.3878</code></pre>
<p>And thus the molar mass of a GC base pair is 618.3878 g/mol.</p>
<p>Now let’s perform the same calculation of molecular mass for an AT base pair.</p>
<pre class="r"><code>library(tidyverse)

# Read the CG base pair PDB file into a tibble. Skip the first 2 rows that
# do not contain the desired data.
AT &lt;- read_table2(file = &quot;../../static/files/t-a.pdb&quot;, 
                       col_names = FALSE, 
                       skip = 2)

# Only the rows with ATOM in column 1 are the ones that should be retained.
AT2 &lt;- AT[grep(&quot;ATOM&quot;,AT$X1), ]

AT.atoms&lt;- substr(as.data.frame(AT2)[,3], 1, 1)

# Make a table with the total number of atoms of each type.
AT.table &lt;- table(AT.atoms)
AT.table</code></pre>
<pre><code>## AT.atoms
##  C  H  N  O  P 
## 20 25  7 12  2</code></pre>
<p>This AT base pair has the formula C<sub>20</sub>H<sub>25</sub>N<sub>7</sub>O<sub>12</sub>P<sub>2</sub>.</p>
<p>Now let’s calculate the molecular weight of an AT base pair.</p>
<pre class="r"><code>library(PeriodicTable)

# Change to a data frame.
AT.df &lt;- as.data.frame(AT.table)

# Add a 3rd column that is the atomic mass of each element.
AT.df2 &lt;- cbind(AT.df, MW = PeriodicTable::mass(AT.df[1:nrow(AT.df),1]))

# Add a 4th column that is the total molecular weight of each element
# in the nucleotide base molecule. This is the product of the atomic
# mass and the number of atoms of each element.
AT.df3 &lt;- cbind(AT.df2, MW.tot = AT.df2[,2] * AT.df2[,3])

AT.df3</code></pre>
<pre><code>##   AT.atoms Freq       MW    MW.tot
## 1        C   20 12.01070 240.21400
## 2        H   25  1.00794  25.19850
## 3        N    7 14.00670  98.04690
## 4        O   12 15.99940 191.99280
## 5        P    2 30.97376  61.94752</code></pre>
<pre class="r"><code>sum(AT.df3[,&quot;MW.tot&quot;])</code></pre>
<pre><code>## [1] 617.3997</code></pre>
<p>Thus an AT base pair has a molar mass of 617.3997 vs. 618.3878 for a GC base pair. This is equivalent to a difference of 0.16%, or less than one fifth of one percent between the base pairs, a negligible amount.</p>
<p>A rule of thumb is that the <a href="https://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/biotech-basics/molecular-facts-and-figures.pdf?sfvrsn=4563407_4">average weight of a DNA base pair is 650 daltons</a>. A dalton weighs 1.66054 x10<sup>-24</sup> g, and so 650 daltons weigh 1.079351 zg. According to this rule, the 4.64 Mb genome of <em>E. coli</em> K12 would weigh 4.64 x10<sup>6</sup> bp X 1.0794 x10<sup>-21</sup> g/bp = 5.0081891 fg.</p>
<p>In my previous blogpost on <a href="/post/prokaryotic-genome-size/index.html">prokaryotic genome size</a>, I determined the median prokaryotic genome size was 4.050955 Mbp, whereas the smallest was 0.185014 Mbp and the largest was 16.0407 Mbp.</p>
<p>Let’s start with calculating the mass of the median genome:</p>
<p><span class="math display">\[4.050955 \times 10^{6} bp * \frac{650 Da}{bp} * \frac{1.66054 \times 10^{-24} g}{1 Da} * \frac{1\times10^{15}fg}{1 g} \]</span></p>
<p>= 4.3724023 fg weight of the median genome size.</p>
<p>Using the above formula, the largest genome weighs 17.3135456 fg while the smallest genome weighs 0.199695 fg.</p>
<p>Note that the 650 dalton rule of thumb is described as the mass of one DNA base pair as a sodium salt. However, the value that I obtained is for the mass of a DNA base pair is 618 daltons, a discrepancy of 32 daltons. A sodium atom weighs ~23 daltons, and so even then <strong>there are about 9 daltons that remain unaccounted, and the source of this discrepancy should be identified</strong>.</p>
<p>Also note that on the Thermo Fisher website for <a href="https://www.thermofisher.com/no/en/home/references/ambion-tech-support/rna-tools-and-calculators/dna-and-rna-molecular-weights-and-conversions.html">DNA and RNA Molecular Weights and Conversions</a>, under the heading “Nucleic Acid Molecular Weight Conversions” and subheading “Approximate M.W.’s of Nucleic Acids”, the folowing approximation is listed, which <strong>also deviates from my result of 618 daltons for the weight of a DNA base pair</strong>:</p>
<blockquote>
<p>M.W. of dsDNA = (# nucleotides x 607.4) + 157.9</p>
</blockquote>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>The structure and composition of the 4 nitrogenous bases of DNA (A, T, G, and C) vary as does their molecular weight which ranges from 111.1 daltons for cytosine to 151.13 daltons for guanine. However, in double-stranded DNA, due to the formation of AT and GC base pairs, the difference in molecular weight of the individual bases is offset such that there is less than one fifth of one percent difference in the molecular weight of an AT base pair (617.3997 Da) vs. a GC base pair (618.3878 Da). Hence, differences in prokaryotic genome mass due to GC content variation would be negligible, and sequence length is the most influential factor determining the mass of prokaryotic genomes, which vary from 0.199695 fg for the smallest genome to 17.313546 fg for the largest, with a median mass of 4.372402 fg.</p>
<p>In the next blogpost, I will extrapolate from the mass of a single prokaryotic genome to the mass of prokaryotic community DNA to be expected from the typical amounts of sample material used in DNA extractions.</p>
</div>
<div id="additional-resources" class="section level2">
<h2>Additional Resources</h2>
<p>A summary of useful DNA facts and figures is presented in <a href="https://sfvideo.blob.core.windows.net/sitefinity/docs/default-source/biotech-basics/molecular-facts-and-figures.pdf?sfvrsn=4563407_4">IDT’s Molecular Facts and Figures pdf</a>.</p>
</div>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/genome-weight/">genome weight</a>
  
  <a class="badge badge-light" href="/tags/genomics/">genomics</a>
  
  <a class="badge badge-light" href="/tags/dna-molecular-weight/">DNA molecular weight</a>
  
</div>



    
      








  
  
    
  
  






  
  
  
  
  <div class="media author-card">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/authors/john-christian-gaby/"></a></h5>
      
      
      <ul class="network-icon" aria-hidden="true">
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/post/prokaryotic-genome-size/">Prokaryotic Genome Size</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    
    
    <script src="/js/mathjax-config.js"></script>
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_CHTML-full" integrity="sha256-GhM+5JHb6QUzOQPXSJLEWP7R73CbkisjzK5Eyij4U9w=" crossorigin="anonymous" async></script>
      
    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin="anonymous"></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.f92d7215d2132cd354f657f0bc9cc542.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
